### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by Raizen9** [cypher-network/faucet.miner#15]
The faucet was running on Ubuntu 20.04.5 LTS inside a VM

Unhandled exception. MessagePack.MessagePackSerializationException: Failed to deserialize Miner.Models.Reward value.
 ---> MessagePack.MessagePackSerializationException: Unexpected msgpack code 0 (positive fixint) encountered.
   at MessagePack.MessagePackReader.ThrowInvalidCode(Byte code)
   at MessagePack.MessagePackReader.TryGetBytesLength(Int32& length)
   at MessagePack.MessagePackReader.GetBytesLength()
   at MessagePack.MessagePackReader.ReadBytes()
   at MessagePack.Formatters.Miner_Models_RewardFormatter2.Deserialize(MessagePackReader& reader, MessagePackSerializerOptions options)
   at MessagePack.MessagePackSerializer.Deserialize[T](MessagePackReader& reader, MessagePackSerializerOptions options)
   --- End of inner exception stack trace ---
   at MessagePack.MessagePackSerializer.Deserialize[T](MessagePackReader& reader, MessagePackSerializerOptions options)
   at MessagePack.MessagePackSerializer.Deserialize[T](ReadOnlyMemory`1 buffer, MessagePackSerializerOptions options, CancellationToken cancellationToken)
   at Miner.ViewModels.MinerViewModel.<Connect>b__46_1() in /home/runner/work/faucet.miner/faucet.miner/miner/ViewModels/MinerViewModel.cs:line 197
   at Miner.Helper.AsyncHelper.RunSync[TResult](Func`1 func) in /home/runner/work/faucet.miner/faucet.miner/miner/Helper/AsyncHelper.cs:line 25
   at Miner.ViewModels.MinerViewModel.<Connect>b__46_0(HubConnectionState x) in /home/runner/work/faucet.miner/faucet.miner/miner/ViewModels/MinerViewModel.cs:line 191
   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/AnonymousSafeObserver.cs:line 43
   at System.Reactive.Concurrency.Scheduler.<>c__67`1.<SchedulePeriodic>b__67_0(ValueTuple`2 t) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Services.Emulation.cs:line 79
   at System.Reactive.Concurrency.DefaultScheduler.PeriodicallyScheduledWorkItem`1.<>c.<Tick>b__5_0(PeriodicallyScheduledWorkItem`1 closureWorkItem) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/DefaultScheduler.cs:line 127
   at System.Reactive.Concurrency.AsyncLock.Wait(Object state, Delegate delegate, Action`2 action) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/AsyncLock.cs:line 93
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
   at System.Threading.TimerQueue.FireNextTimers()
Abandon (core dumped)

**Comment by Prusias** [comment]
I ran into the same issue, Ubuntu 18.04.6 LTS on bare metal.

```Unhandled exception. MessagePack.MessagePackSerializationException: Failed to deserialize Miner.Models.Reward value.
 ---> MessagePack.MessagePackSerializationException: Unexpected msgpack code 0 (positive fixint) encountered.
   at MessagePack.MessagePackReader.ThrowInvalidCode(Byte code)
   at MessagePack.MessagePackReader.TryGetBytesLength(Int32& length)
   at MessagePack.MessagePackReader.GetBytesLength()
   at MessagePack.MessagePackReader.ReadBytes()
   at MessagePack.Formatters.Miner_Models_RewardFormatter2.Deserialize(MessagePackReader& reader, MessagePackSerializerOptions options)
   at MessagePack.MessagePackSerializer.Deserialize[T](MessagePackReader& reader, MessagePackSerializerOptions options)
   --- End of inner exception stack trace ---
   at MessagePack.MessagePackSerializer.Deserialize[T](MessagePackReader& reader, MessagePackSerializerOptions options)
   at Miner.ViewModels.MinerViewModel.<Connect>b__46_1() in /home/runner/work/faucet.miner/faucet.miner/miner/ViewModels/MinerViewModel.cs:line 200
   at Miner.Helper.AsyncHelper.RunSync[TResult](Func`1 func) in /home/runner/work/faucet.miner/faucet.miner/miner/Helper/AsyncHelper.cs:line 25
   at Miner.ViewModels.MinerViewModel.<Connect>b__46_0(HubConnectionState x) in /home/runner/work/faucet.miner/faucet.miner/miner/ViewModels/MinerViewModel.cs:line 202
   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/AnonymousSafeObserver.cs:line 54
   at System.Reactive.Concurrency.Scheduler.<>c__67`1.<SchedulePeriodic>b__67_0(ValueTuple`2 t) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Services.Emulation.cs:line 79
   at System.Reactive.Concurrency.DefaultScheduler.PeriodicallyScheduledWorkItem`1.<>c.<Tick>b__5_0(PeriodicallyScheduledWorkItem`1 closureWorkItem) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/DefaultScheduler.cs:line 127
   at System.Reactive.Concurrency.AsyncLock.Wait(Object state, Delegate delegate, Action`2 action) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/AsyncLock.cs:line 93
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
   at System.Threading.TimerQueue.FireNextTimers()
[1]    12294 abort (core dumped) 
```

**Comment by Prusias** [comment]
Still occurring on 0.0.9
